# Generated by Django 6.1.1 on 2026-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RIDER', 'Rider'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
