# Generated by Django 6.1.1 on 2026-09-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
