# Generated by Django 6.1.1 on 2026-09-23 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='riders/profile/')),
                ('date_of_birth', models.DateField()),
                ('rented_vehicle', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('CAR', 'Car')], max_length=20)),
                ('ghana_card_number', models.CharField(max_length=15, unique=True)),
                ('ghana_card_image', models.ImageField(upload_to='riders/ghana_cards/')),
                ('is_student', models.BooleanField(default=False)),
                ('student_id_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
