# Generated by Django 6.1.1 on 2026-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
