# Generated by Django 6.1.1 on 2026-09-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_riderprofile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
