# Generated by Django 6.1.1 on 2026-09-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_riderprofile_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
