# Generated by Django 6.1.1 on 2026-09-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_riderprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
