# Generated by Django 6.1.1 on 2026-09-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_alter_riderprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='ghana_card_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
