# Generated by Django 6.1.1 on 2026-09-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0006_alter_riderprofile_ghana_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='date_of_birth',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
