# Generated by Django 6.1.1 on 2026-09-23 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('rider', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('FOOD', 'Food')], default='FOOD', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('PICKED UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Online'), ('ON DELIVERY', 'On Delivery')], default='ONLINE', max_length=30)),
                ('delivery_code', models.CharField(blank=True, editable=False, max_length=4)),
                ('order_id', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customerprofile')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rider.riderprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_at_order_time', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menu_item_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor.menuitemvariant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='order.order')),
            ],
        ),
    ]
